select ACTUAL_JOB.JOB_IDENTIFIER as IDENTIFIER, STATUS.NAME as STATUS_NAME, STATUS.CODE as STATUS_CODE 
from ACTUAL_JOB 
join SCHEDULER on (ACTUAL_JOB.FK_DESIRED_SCH = SCHEDULER.OBJECT_ID and SCHEDULER.NAME = ?)
join REFERENCE_DATA STATUS on (ACTUAL_JOB.FRK_STATUS = STATUS.CODE and ACTUAL_JOB.FSK_STATUS = STATUS.SUBCLASS)
where ACTUAL_JOB.JOB_IDENTIFIER = ?