select ACTUAL_JOB.JOB_IDENTIFIER as IDENTIFIER, STATUS.NAME as STATUS_NAME, STATUS.CODE as STATUS_CODE 
from ACTUAL_JOB, ACTUAL_JOB_STEP 
join REFERENCE_DATA STATUS on (ACTUAL_JOB_STEP.FRK_STATUS = STATUS.CODE and ACTUAL_JOB_STEP.FSK_STATUS = STATUS.SUBCLASS)
where ACTUAL_JOB.OBJECT_ID = ACTUAL_JOB_STEP.FK_JOB and  ACTUAL_JOB.JOB_IDENTIFIER = ? and ACTUAL_JOB_STEP.SEQUENCE = ?